# Generated by Django 5.0.3 on 2024-04-30 18:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rua', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Farm',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('fk_farm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.farm')),
            ],
            options={
                'db_table': 'Person',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('fk_farm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.farm')),
                ('fk_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.person')),
            ],
            options={
                'db_table': 'Photo',
            },
        ),
    ]
